# Generated by Django 2.1.4 on 2019-06-17 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('acc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('acc_number', models.IntegerField(blank=True, null=True)),
                ('acc_type', models.CharField(blank=True, max_length=255, null=True)),
                ('acc_opened', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('cl_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cl_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cl_surname', models.CharField(blank=True, max_length=255, null=True)),
                ('cl_pwd', models.IntegerField(blank=True, null=True)),
                ('cl_idnumber', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('tr_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tr_amount', models.FloatField(blank=True, null=True)),
                ('tr_date', models.DateField(blank=True, null=True)),
                ('tr_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acc_transactions', to='api.Account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='acc_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cl_accounts', to='api.Client'),
        ),
    ]
