# Generated by Django 2.1.4 on 2019-06-15 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_id', models.IntegerField(blank=True, null=True)),
                ('acc_number', models.IntegerField(blank=True, null=True)),
                ('acc_type', models.CharField(blank=True, max_length=255, null=True)),
                ('acc_opened', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cl_surname', models.CharField(blank=True, max_length=255, null=True)),
                ('cl_pwd', models.IntegerField(blank=True, null=True)),
                ('cl_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tr_id', models.IntegerField(blank=True, null=True)),
                ('tr_amount', models.FloatField(blank=True, null=True)),
                ('tr_date', models.DateField(blank=True, null=True)),
                ('tr_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acc_transactions', to='api.Account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='acc_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cl_accounts', to='api.Client'),
        ),
    ]
